apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ExternalName
  externalName: traceability.int.demo.catena-x.net
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: http
    port: 80
    targetPort: 80
  