{{- if .Values.imagePullSecret.dockerconfigjson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-traceability-foss-frontend.fullname" . }}-imagepullsecret
  labels:
    {{- include "product-traceability-foss-frontend.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
  {{- end }}